import type { InstallSpec } from '../../model/installSpec'
import type { EmitResult } from '../types'
import { applyUnknownFlags, extraSectionBlocks } from './passthrough'
import {
  constantLine,
  identityLines,
  ksBlock,
  localeLines,
  networkLines,
  packagesBlock,
  SLOT_DEFAULTS,
  securityLines,
  sourceLines,
  sshHardeningPost,
  storageLines,
} from './sections'

const splitRaw = (s: string): string[] => (s ? s.split('\n') : [])

/**
 * Render an InstallSpec to an Anaconda Kickstart file. Pure: same spec → same
 * bytes. Cross-format gaps (e.g. AppArmor) are surfaced as warnings, never
 * worked around with injected shell.
 */
export function emitKickstart(spec: InstallSpec): EmitResult {
  const header = [
    `# Kickstart generated by linux-generators v${spec.meta.generatorVersion}`,
    ...(spec.meta.buildStamp ? [`# build-stamp: ${spec.meta.buildStamp}`] : []),
  ]

  const ks = spec.passthrough.kickstart
  const storage = ks.rawStorage.length > 0 ? ks.rawStorage : storageLines(spec)

  const commands = applyUnknownFlags(
    [
      constantLine(spec, 'mode', SLOT_DEFAULTS.mode),
      ...sourceLines(spec),
      ...localeLines(spec),
      ...networkLines(spec),
      ...identityLines(spec),
      ...storage,
      constantLine(spec, 'bootloader', SLOT_DEFAULTS.bootloader),
      ...securityLines(spec),
      ...ks.extraCommands,
      constantLine(spec, 'firstboot', SLOT_DEFAULTS.firstboot),
      constantLine(spec, 'power', SLOT_DEFAULTS.power),
    ],
    ks.unknownFlags,
  )

  const pre = ksBlock(ks.preHeader || '%pre --log=/var/log/ks-pre.log', [
    ...spec.scripts.pre,
    ...splitRaw(spec.scripts.rawKickstartPre),
  ])

  const post = ksBlock(ks.postHeader || '%post --log=/var/log/ks-post.log', [
    ...sshHardeningPost(spec),
    ...spec.scripts.post,
    ...splitRaw(spec.scripts.rawKickstartPost),
  ])

  const content = `${[
    ...header,
    ...commands,
    '',
    ...packagesBlock(spec),
    '',
    ...pre,
    ...post,
    ...extraSectionBlocks(ks.extraSections),
  ]
    .join('\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()}\n`

  const diagnostics =
    spec.security.apparmor !== 'disabled'
      ? [
          {
            severity: 'warning' as const,
            field: 'security.apparmor',
            message: 'AppArmor is not configurable from Kickstart; setting ignored on this target.',
          },
        ]
      : []

  return {
    files: [{ filename: 'ks.cfg', content, language: 'kickstart' }],
    diagnostics,
  }
}
