import { defaultTargetForFormat, freshDefaultSpec, type InstallSpec } from '@engines/model'
import { describe, expect, it } from 'vitest'
import { PRESEED_FIXTURES } from '@/__fixtures__/debianSpecs'
import { emitPreseed } from './emitPreseed'

const debianSpec = (mutate?: (d: InstallSpec) => void): InstallSpec => {
  const s = freshDefaultSpec()
  Object.assign(s.target, defaultTargetForFormat('preseed'))
  s.packages.groups = []
  mutate?.(s)
  return s
}

describe('emitPreseed golden', () => {
  it.each(PRESEED_FIXTURES)('golden output: $name', ({ spec }) => {
    expect(emitPreseed(spec).files[0]?.content).toMatchSnapshot()
  })
})

describe('emitPreseed (skeleton)', () => {
  it('produces a single preseed.cfg file', () => {
    const { files } = emitPreseed(debianSpec())
    expect(files).toHaveLength(1)
    expect(files[0]?.filename).toBe('preseed.cfg')
    expect(files[0]?.language).toBe('preseed')
  })

  it('emits the generator header and the locale/grub/finish directives', () => {
    const out = emitPreseed(debianSpec()).files[0]?.content ?? ''
    expect(out.startsWith('# Preseed generated by linux-generators')).toBe(true)
    expect(out).toContain('d-i debian-installer/locale string en_US.UTF-8')
    expect(out).toContain('d-i keyboard-configuration/xkb-keymap select us')
    expect(out).toContain('d-i grub-installer/bootdev string default')
    expect(out).toContain('d-i finish-install/reboot_in_progress note')
  })

  it('appends a raw preseed passthrough block verbatim', () => {
    const out = emitPreseed(
      debianSpec((d) => {
        d.scripts.rawPreseed = 'd-i some/custom/question string value'
      }),
    ).files[0]?.content
    expect(out).toContain('d-i some/custom/question string value')
  })

  it('emits scripts.earlyCommands as a preseed/early_command directive', () => {
    // regression: the form exposes early-commands for Debian; they must not be
    // silently dropped at emit (only late_command was wired originally).
    const out = emitPreseed(
      debianSpec((d) => {
        d.scripts.earlyCommands = ['anna-install foo']
      }),
    ).files[0]?.content
    expect(out).toContain('d-i preseed/early_command string anna-install foo')
  })

  it('is deterministic (same spec → identical bytes)', () => {
    expect(emitPreseed(debianSpec()).files[0]?.content).toBe(
      emitPreseed(debianSpec()).files[0]?.content,
    )
  })
})
