import type { InstallSpec } from '../../model/installSpec'
import type { Diagnostic } from '../../types'
import { crossFormatDrops } from '../crossFormat'
import type { EmitResult } from '../types'
import { buildEarlyCommand, buildLateCommand } from './lateCommand'
import {
  finishingLines,
  identityLines,
  localeLines,
  networkLines,
  packagesLines,
  storageLines,
} from './sections'

/**
 * Render an InstallSpec to a Debian Preseed `preseed.cfg`. Pure: same spec →
 * same bytes. Line-based `d-i <owner>/<question> <type> <value>` directives,
 * assembled in canonical order. Cross-format gaps surface as warnings; features
 * preseed can't express natively (SSH keys, ufw, AppArmor) are realized in the
 * single `late_command` rather than dropped.
 */
export function emitPreseed(spec: InstallSpec): EmitResult {
  const header = [
    `# Preseed generated by linux-generators v${spec.meta.generatorVersion}`,
    ...(spec.meta.buildStamp ? [`# build-stamp: ${spec.meta.buildStamp}`] : []),
  ]

  // Only the user-authored raw block can contain blank runs; every section emits
  // single newline-free lines, so normalize just `raw` rather than scan the whole doc.
  const raw = spec.scripts.rawPreseed.trim().replace(/\n{3,}/g, '\n\n')

  const content = `${[
    ...header,
    ...localeLines(spec),
    ...networkLines(spec),
    ...buildEarlyCommand(spec),
    ...storageLines(spec),
    ...identityLines(spec),
    ...packagesLines(spec),
    ...buildLateCommand(spec),
    ...finishingLines(spec),
    ...(raw ? [raw] : []),
  ]
    .join('\n')
    .trimEnd()}\n`

  const diagnostics: Diagnostic[] = crossFormatDrops(spec, 'preseed').map((drop) => ({
    severity: 'warning',
    field: drop.field,
    message: drop.message,
  }))

  return {
    files: [{ filename: 'preseed.cfg', content, language: 'preseed' }],
    diagnostics,
  }
}
